/* global React */
const {
  createContext: createContextI,
  useContext: useContextI,
  useEffect: useEffectI,
  useMemo: useMemoI,
  useState: useStateI,
} = React;

const SITE_COPY = {
  nl: {
    locale: "nl-BE",
    htmlLang: "nl",
    title: "Les Trois Loups · Vakantiehuis Hardelot, Opaalkust",
    description: "Karaktervol familiehuis op 100 m van het strand van Hardelot. Voor 6–8 personen, met tuin, houtkachel en garage.",
    nav: { house: "De woning", gallery: "Galerij", location: "Locatie", reviews: "Reviews", rates: "Tarieven", faq: "FAQ", cta: "Check je data", languages: "Kies je taal" },
    hero: {
      meta: "Les Trois Loups · Hardelot-Plage",
      title: "Een echt familiehuis, honderd meter van het strand.",
      lede: "Ruimte voor zes tot acht gasten, met vier slaapkamers, twee badkamers, een houtkachel, tuin en garage. Het centrum ligt gewoon op wandelafstand.",
      cta: "Check prijs & voorkeursdata", photos: "Bekijk de echte foto's", features: "Belangrijkste kenmerken",
      guests: "gasten", bedrooms: "slaapkamers", bathrooms: "badkamers", sea: "tot zee"
    },
    trust: { label: "Boekingszekerheid", reviews: "Geverifieerde reviews", owners: "Rechtstreeks bij Dany en Patricia", payment: "Geen onmiddellijke betaling" },
    about: {
      title: "Een gerenoveerde karaktervilla, geen vakantiepark.",
      lede: "Volledig gerenoveerd met behoud van karakter. Ideaal voor gezinnen die dicht bij zee willen verblijven zonder de auto nodig te hebben — strand, winkels en restaurants liggen op wandelafstand.",
      body: "Twee verdiepingen, twee badkamers en een afgesloten tuin op het zuiden. De salon met ingebouwde houtkachel werkt het hele jaar door als hart van het huis. De garage is groot genoeg voor fietsen, kinderwagens, surfboards en strandspeelgoed.",
      tags: ["Volledig uitgeruste keuken", "Houtkachel", "Afgesloten tuin", "Terras zuid + west", "Privéparking", "Babyspullen aanwezig"],
      imageSalon: "Salon met houtkachel", imageLiving: "Open leefruimte en eethoek",
      ground: "Gelijkvloers", first: "Eerste verdieping",
      groundRooms: ["Salon met ingebouwde houtkachel", "Open keuken, volledig uitgerust", "Slaapkamer, tweepersoonsbed", "Badkamer met bad/douche, dubbele lavabo", "Aparte wc · nachthal"],
      firstRooms: ["Slaapkamer 2", "Slaapkamer 3", "Kinder-/babykamer met bedje", "Badkamer met douche, lavabo, wc"], optional: "opt."
    },
    gallery: {
      title: "Door het huis, en even naar buiten.",
      lede: "Actuele foto's uit de MediaVakanties-advertentie. Zo zie je het echte huis en de werkelijke indeling. Klik op een beeld om te vergroten.",
      enlarge: "Vergroot",
      tabs: { buiten: "Buiten & entree", living: "Leefruimte & keuken", slaap: "Slaapkamers", bad: "Badkamers" },
      captions: {
        buiten: ["Les Trois Loups vanaf de straat", "Overdekte entree", "Terras met buitenhaard", "Privéparking en inpandige garage"],
        living: ["Leefruimte en grote eettafel", "Zithoek met houtkachel", "Keuken"],
        slaap: ["Slaapkamer met tweepersoonsbed", "Tweede tweepersoonskamer", "Kamer met twee enkele bedden", "Kinderkamer", "Kinderstoel en babyuitrusting"],
        bad: ["Badkamer op het gelijkvloers", "Douchekamer boven"]
      }
    },
    amenities: {
      title: "Wat je vindt als je binnenstapt.",
      lede: "Praktisch uitgerust voor een gezinsverblijf. Bedlinnen is optioneel; de overige details worden samen met de definitieve offerte bevestigd.",
      linen: "Bedlinnen en handdoeken: optioneel bij te boeken (€12 p.p.) — of zelf meebrengen.",
      items: [["Wifi", "internet"], ["Televisie", "salon"], ["Oven & microgolf", ""], ["Wasmachine", ""], ["Vaatwasser", ""], ["Koffie & waterkoker", ""], ["Houtkachel", ""], ["Barbecue & tuinmeubilair", ""], ["Afgesloten tuin", "200 m²"], ["Privéparking + garage", ""], ["Kinderbed, stoel, badje", "voor 0–3 j."], ["Gezelschapsspellen", ""], ["Bibliotheek", "FR · NL · EN"], ["Bad & douche", ""], ["Huisdieren", "op aanvraag"], ["Niet-rokerswoning", "muted"]]
    },
    location: {
      title: "Praktisch dichtbij, veel te zien.", lede: "Van ochtendbrood tot een uitstap op een regendag: je ziet meteen wat dichtbij ligt en waarvoor je best even de auto neemt.",
      introTitle: "Strand, centrum en dagelijkse boodschappen dichtbij.", intro: "De afstanden zijn richtinggevend en afgestemd op de MediaVakanties-advertentie. Controleer voor een uitstap altijd even de actuele openingsuren.",
      groups: [
        { label: "Praktisch dichtbij", sub: "afstanden uit de MediaVakanties-advertentie", items: [["Strandopgang", "Zee en strand zonder auto", "± 100 m"], ["Centrum Hardelot", "Winkels, bakker, restaurants en boodschappen", "± 500 m"], ["Duinen, bos en natuur", "Wandelen, fietsen en rustige routes vlakbij", "± 300 m"], ["Tennisclub", "Sportoptie dichtbij voor gezinnen", "± 2,2 km"]] },
        { label: "Eten & boodschappen", sub: "praktisch voor aankomst en elke ochtend", items: [["Bakker & ontbijt", "Brood, koffiekoeken en picknick voor het strand", "± 500 m"], ["Restaurants in Hardelot", "Lunch na het strand of diner met kinderen", "± 500 m"], ["Kleine boodschappen", "Handig als je zonder auto wil verblijven", "± 500 m"], ["Grotere boodschappen", "Voor weekinkopen en koken in de vakantiekeuken", "korte rit"]] },
        { label: "Bezienswaardigheden", sub: "voor regenweer, daguitstappen en kinderen", items: [["Château d'Hardelot", "Kasteel, tuinen en cultuurprogramma", "± 3 km"], ["Nausicaá Boulogne", "Groot aquarium, ideaal bij minder strandweer", "10,4 km"], ["Maréis in Étaples", "Interactieve ontdekking van visserij en zeedieren", "± 20 km"], ["Le Touquet", "Markt, winkels, golf en strand", "± 12 km"], ["Boulogne-sur-Mer", "Havenstad, oude stad en extra horeca", "± 14 km"], ["Bagatelle", "Familiepretpark voor een volledige daguitstap", "23,2 km"], ["Cap Blanc-Nez & Gris-Nez", "Krijtrotsen, wandelroutes en vergezichten", "± 30 km"]] }
      ]
    },
    families: {
      title: "Waarom families graag terugkomen.", lede: "Het huis is gemaakt voor wie graag met (klein)kinderen op vakantie gaat én voor wie het rustig wil houden. Geen vakantieparkdrukte, wel alle comfort.",
      items: [["Strand zonder auto", "Vijf minuten met de kinderwagen — geen parkeerstress, geen file."], ["Babyspullen aanwezig", "Bedje, kinderstoel, badje. Eén koffer minder onderweg."], ["Afgesloten tuin", "Spelen, eten en koffie drinken zonder dat iemand weg kan lopen."], ["Garage voor materiaal", "Fietsen, kinderwagens, surfboards en strandtenten. Allemaal binnen."], ["Bos & duinen dichtbij", "Wandel- en fietsroutes voor jong en oud, vlak bij de voordeur."], ["Avonden bij de houtkachel", "Boeken, spelletjes en een glas wijn. Buiten mag het wat regenen."]]
    },
    reviews: {
      title: "Het oordeel van wie er sliep.", lede: "Samenvattingen uit gecontroleerde MediaVakanties-reviews. De rode draad: ligging, comfort, gezinsvriendelijkheid en snelle communicatie.",
      note: "Reviews zijn kort samengevat uit MediaVakanties.", source: "Bekijk de advertentie en bronreviews", platform: "MediaVakanties",
      items: [["Tweede verblijf en opnieuw tevreden: praktisch huis, sterke ligging en kinderen blij.", "Aug 2025"], ["De gast omschrijft het verblijf als perfect geregeld, zonder minpunten te melden.", "Jun 2023"], ["Aangenaam familiehuis met alle nodige comfort en een ligging dicht bij het strand.", "Aug 2020"], ["Smaakvol huis met alles aanwezig, vlak bij het strand en goed voor een ontspannen verblijf.", "Nov 2019"], ["Gezellig huis in een rustige buurt, super dicht bij strand en centrum, met snelle eigenaars.", "Aug 2019"], ["Mooi ingericht huis, dicht bij zee en stad, met rustige ruimtes voor gezinnen.", "Mei 2018"]]
    },
    rates: {
      title: "Wat het kost, zonder kleine lettertjes.", lede: "De gepubliceerde weekprijs ligt tussen €750 en €1.150. Dany en Patricia bevestigen altijd eerst de exacte prijs, beschikbaarheid en kosten voor jouw data.",
      from: "Vanafprijs", max: "Maximum gepubliceerde weekprijs", week: "/week", adSource: "Volgens de actuele MediaVakanties-advertentie", exact: "Exacte prijs hangt af van periode en verblijfsduur",
      low: ["Verblijven vanaf 2 nachten mogelijk", "Weekend en midweek op aanvraag", "Geen betaling bij de eerste aanvraag", "Persoonlijke bevestiging door de eigenaar"],
      high: ["Schoolvakanties snel aanvragen", "Beschikbaarheid wordt apart gecontroleerd", "Vaste kosten staan vooraf in het voorstel", "Huurovereenkomst vóór betaling"],
      meta: [["Waarborg", "€500, terugbetaald na controle"], ["Voorschot", "30% bij reservatie"], ["Schoonmaak", "€85, bij voorstel bevestigd"], ["Toeristenbelasting", "Bij offerte bevestigd"], ["Bedlinnen", "Optioneel €12 p.p."], ["Huisdier", "€35/week, na akkoord"], ["Saldo", "1 maand voor aankomst"]]
    },
    booking: {
      title: "Kies je dagen, krijg meteen een richtprijs.", body: "De berekening is een eerste indicatie op basis van seizoen, nachten, gasten en vaste kosten. Dany en Patricia bevestigen daarna persoonlijk de beschikbaarheid, totaalprijs en praktische afspraken.",
      qualifiers: [["Geen onmiddellijke betaling.", "Je maakt eerst een vrijblijvende aanvraag klaar."], ["Richtprijs, geen belofte.", "De definitieve prijs volgt na controle van kalender en kosten."], ["Persoonlijk contact.", "Je praat met de eigenaar, niet met een agentschap."]],
      ownerNames: "Dany en Patricia", owners: "Eigenaars van Les Trois Loups", ownerNote: "Een karaktervol familiehuis dicht bij zee, waar meerdere generaties comfortabel samen kunnen verblijven."
    },
    faq: {
      title: "De antwoorden waar gasten naar vragen.", lede: "Vind je hier je vraag niet? Stuur een bericht via de geverifieerde MediaVakanties-advertentie; je krijgt persoonlijk antwoord van de verhuurder.",
      items: [["Hoe ver is het strand precies?", "Ongeveer 100 meter via een rustige straat met voetpad. Vijf minuten wandelen met kinderen en speelgoed — sneller zonder."], ["Is de woning geschikt voor jonge kinderen?", "Ja. Babybedje, kinderstoel en babybadje zijn aanwezig. De tuin is volledig afgesloten en de slaapkamers liggen verspreid over twee verdiepingen."], ["Zijn huisdieren toegestaan?", "In principe ja, maar uitsluitend na voorafgaand akkoord. Vermeld in je aanvraag het type en aantal dieren. Forfait €35."], ["Is er parking?", "Er is privéparking voor één wagen en een inpandige garage. Vraag bij meerdere wagens vooraf naar de mogelijkheden in de buurt."], ["Is er wifi?", "Ja. Vraag bij specifieke eisen zoals videowerk vooraf naar snelheid en dekking."], ["Is bedlinnen inbegrepen?", "Optioneel bij te boeken (€12 p.p.) of zelf meebrengen. Dekens en kussens zijn altijd voorzien."], ["Wat is het minimumverblijf?", "De advertentie vermeldt verblijven vanaf 2 nachten. Voor drukke periodes bevestigt de eigenaar de minimale verblijfsduur."], ["Hoe werkt reserveren?", "Je maakt via deze website een aanvraag klaar en verstuurt die via MediaVakanties. De eigenaar bevestigt beschikbaarheid en stuurt een definitief voorstel."], ["Kan ik een weekend of midweek boeken?", "Ja, buiten hoogseizoen kan je een weekend of midweek reserveren vanaf 2 nachten."], ["Zijn er winkels en restaurants dichtbij?", "Ja. Het centrum van Hardelot ligt op ongeveer 500 meter. Grotere boodschappen en extra horeca liggen op korte rijafstand."]]
    },
    contact: { title: "Een vraag, vrijblijvend?", lede: "Kies eerst je voorkeursdata. Voor de definitieve aanvraag en geverifieerde contactgegevens verwijzen we naar de bestaande MediaVakanties-advertentie.", ask: "Stel je vraag", check: "Beschikbaarheid checken", verified: "Geverifieerd contact", via: "Contacteer via MediaVakanties", note: "Rechtstreeks contact met de particuliere verhuurder · geen onmiddellijke betaling · voorwaarden vóór reservatie.", listing: "MediaVakanties-advertentie" },
    footer: { region: "Opaalkust" },
    mobile: { from: "vanaf", week: "/week", check: "Check prijs" },
    lightbox: { close: "Sluit", previous: "Vorige foto", next: "Volgende foto" },
    form: {
      title: "Kies je voorkeursdata", from: "vanaf", week: "/ week", previousMonth: "Vorige maand", nextMonth: "Volgende maand", weekdays: ["Ma", "Di", "Wo", "Do", "Vr", "Za", "Zo"], selected: "Geselecteerd", confirm: "Beschikbaarheid wordt persoonlijk bevestigd",
      arrival: "Aankomst", departure: "Vertrek", adults: "Volwassenen", children: "Kinderen", childrenSub: "t.e.m. 12 jaar", decrease: "verminderen", increase: "verhogen", pet: "Huisdier mee", petSub: "Onderling akkoord, +€35", petAria: "Huisdier meenemen", name: "Naam", email: "E-mail", phone: "Telefoon", addMessage: "+ Bericht toevoegen", message: "Bericht (optioneel)", messagePlaceholder: "Aankomstuur, vragen, bijzonderheden …",
      cleaning: "Schoonmaak", tax: "Toeristenbelasting", toConfirm: "te bevestigen", petFee: "Huisdier", total: "Richtprijs excl. belasting", nights: "nachten", chooseDates: "Kies aankomst en vertrek om een prijsopgave te zien. Minimum 2 nachten.", submit: "Maak mijn aanvraag klaar", disclaimer: "Geen onmiddellijke betaling. Deze stap verstuurt nog niets; je controleert en verstuurt daarna via MediaVakanties.", ready: "Je aanvraag is klaar.", readyBody: "Kopieer de samenvatting en open daarna de geverifieerde advertentie om ze naar de verhuurder te sturen.", copy: "Kopieer aanvraag", copied: "Aanvraag gekopieerd", open: "Open MediaVakanties",
      priceTitle: "Prijsindicatie", priceEmpty: "Selecteer eerst aankomst en vertrek voor een voorlopige prijsinschatting. De eigenaar bevestigt de definitieve prijs en beschikbaarheid.", attractive: "Aantrekkelijke periode", normal: "Normale richtprijs", busy: "Drukke periode", attractiveText: "Deze periode valt gunstig uit in de richtberekening. De eigenaar controleert nadien de kalender en bevestigt het finale voorstel.", normalText: "Deze prijs ligt binnen de normale richtzone voor deze woning en periode.", busyText: "Deze periode valt duurder uit door seizoen, vakantieperiode of korte verblijfsduur. Een aangrenzende week kan soms voordeliger zijn.", period: "Periode", guests: "Gasten", beach: "Strand", bedrooms: "Slaapkamers", seasonHigh: "hoogseizoen", seasonShoulder: "tussenseizoen", seasonChristmas: "kerstvakantie", seasonLow: "buiten seizoen", yes: "ja", estimate: "Deze inschatting is indicatief en geen prijsgarantie. De definitieve prijs, beschikbaarheid en voorwaarden worden persoonlijk bevestigd.", zone: "richtzone",
      inquiryTitle: "Reservatie-aanvraag Les Trois Loups", preferredDates: "Voorkeursdata", party: "Gezelschap", adultsWord: "volwassene(n)", childrenWord: "kind(eren)", petRequest: "huisdier op aanvraag", websitePrice: "Richtprijs website (excl. te bevestigen toeristenbelasting)", messageWord: "Bericht", requestConfirm: "Graag ontvang ik bevestiging van beschikbaarheid, totaalprijs en voorwaarden.", toast: "Aanvraag klaargezet voor {from} → {to}. Kopieer ze en verstuur via MediaVakanties."
    }
  },

  fr: {
    locale: "fr-FR", htmlLang: "fr", title: "Les Trois Loups · Maison de vacances à Hardelot", description: "Maison de famille de caractère à 100 m de la plage d'Hardelot. Pour 6 à 8 personnes, avec jardin, poêle à bois et garage.",
    nav: { house: "La maison", gallery: "Photos", location: "Situation", reviews: "Avis", rates: "Tarifs", faq: "FAQ", cta: "Vérifier les dates", languages: "Choisir la langue" },
    hero: { meta: "Les Trois Loups · Hardelot-Plage", title: "Une vraie maison de famille, à cent mètres de la plage.", lede: "De la place pour six à huit personnes, avec quatre chambres, deux salles de bains, un poêle à bois, un jardin et un garage. Le centre est accessible à pied.", cta: "Voir le prix et les dates", photos: "Voir les vraies photos", features: "Caractéristiques principales", guests: "personnes", bedrooms: "chambres", bathrooms: "salles de bains", sea: "de la mer" },
    trust: { label: "Réservation en confiance", reviews: "Avis vérifiés", owners: "En direct avec Dany et Patricia", payment: "Aucun paiement immédiat" },
    about: { title: "Une villa de caractère rénovée, loin des villages vacances.", lede: "Entièrement rénovée en conservant son caractère. Idéale pour les familles qui veulent séjourner près de la mer sans dépendre de la voiture : plage, commerces et restaurants sont accessibles à pied.", body: "Deux étages, deux salles de bains et un jardin clos orienté au sud. Le salon avec poêle à bois reste le cœur de la maison toute l'année. Le garage accueille vélos, poussettes, planches de surf et jeux de plage.", tags: ["Cuisine entièrement équipée", "Poêle à bois", "Jardin clos", "Terrasses sud et ouest", "Parking privé", "Équipement bébé"], imageSalon: "Salon avec poêle à bois", imageLiving: "Grande pièce de vie et salle à manger", ground: "Rez-de-chaussée", first: "Premier étage", groundRooms: ["Salon avec poêle à bois intégré", "Cuisine ouverte entièrement équipée", "Chambre avec lit double", "Salle de bains avec baignoire/douche et double vasque", "WC séparé · hall de nuit"], firstRooms: ["Chambre 2", "Chambre 3", "Chambre enfant/bébé avec lit", "Salle de douche avec lavabo et WC"], optional: "opt." },
    gallery: { title: "À travers la maison, puis dehors.", lede: "Photos actuelles de l'annonce MediaVacances. Vous voyez la vraie maison et sa disposition. Cliquez sur une photo pour l'agrandir.", enlarge: "Agrandir", tabs: { buiten: "Extérieur & entrée", living: "Séjour & cuisine", slaap: "Chambres", bad: "Salles de bains" }, captions: { buiten: ["Les Trois Loups depuis la rue", "Entrée couverte", "Terrasse avec foyer extérieur", "Parking privé et garage intégré"], living: ["Pièce de vie et grande table", "Salon avec poêle à bois", "Cuisine"], slaap: ["Chambre avec lit double", "Deuxième chambre double", "Chambre avec deux lits simples", "Chambre d'enfant", "Chaise haute et équipement bébé"], bad: ["Salle de bains au rez-de-chaussée", "Salle de douche à l'étage"] } },
    amenities: { title: "Tout ce qui vous attend sur place.", lede: "Équipée pour un séjour en famille. Le linge de lit est disponible en option ; les autres détails sont confirmés avec l'offre définitive.", linen: "Draps et serviettes : en option (€12 p.p.) ou à apporter.", items: [["Wi-Fi", "internet"], ["Télévision", "salon"], ["Four & micro-ondes", ""], ["Lave-linge", ""], ["Lave-vaisselle", ""], ["Cafetière & bouilloire", ""], ["Poêle à bois", ""], ["Barbecue & mobilier de jardin", ""], ["Jardin clos", "200 m²"], ["Parking privé + garage", ""], ["Lit, chaise et bain bébé", "0–3 ans"], ["Jeux de société", ""], ["Bibliothèque", "FR · NL · EN"], ["Baignoire & douche", ""], ["Animaux", "sur demande"], ["Maison non-fumeur", "muted"]] },
    location: { title: "Tout près, beaucoup à découvrir.", lede: "Du pain du matin à une sortie un jour de pluie : voyez immédiatement ce qui se fait à pied et ce qui mérite un court trajet.", introTitle: "Plage, centre et courses quotidiennes à proximité.", intro: "Les distances sont indicatives et basées sur l'annonce MediaVacances. Vérifiez toujours les horaires actuels avant une sortie.", groups: [
      { label: "Tout près", sub: "distances selon l'annonce MediaVacances", items: [["Accès à la plage", "La mer sans voiture", "± 100 m"], ["Centre d'Hardelot", "Commerces, boulangerie, restaurants et courses", "± 500 m"], ["Dunes, forêt et nature", "Promenades et pistes cyclables à proximité", "± 300 m"], ["Club de tennis", "Activité sportive proche pour les familles", "± 2,2 km"]] },
      { label: "Manger & faire les courses", sub: "pratique à l'arrivée et chaque matin", items: [["Boulangerie & petit-déjeuner", "Pain, viennoiseries et pique-nique", "± 500 m"], ["Restaurants à Hardelot", "Déjeuner après la plage ou dîner en famille", "± 500 m"], ["Petites courses", "Pratique sans voiture", "± 500 m"], ["Grandes courses", "Pour les achats de la semaine", "court trajet"]] },
      { label: "À découvrir", sub: "jours de pluie, excursions et enfants", items: [["Château d'Hardelot", "Château, jardins et programme culturel", "± 3 km"], ["Nausicaá Boulogne", "Grand aquarium, idéal par temps couvert", "10,4 km"], ["Maréis à Étaples", "Découverte interactive de la pêche et de la vie marine", "± 20 km"], ["Le Touquet", "Marché, boutiques, golf et plage", "± 12 km"], ["Boulogne-sur-Mer", "Port, vieille ville et restaurants", "± 14 km"], ["Bagatelle", "Parc d'attractions familial", "23,2 km"], ["Caps Blanc-Nez & Gris-Nez", "Falaises, randonnées et panoramas", "± 30 km"]] }
    ] },
    families: { title: "Pourquoi les familles reviennent.", lede: "La maison convient aux vacances avec enfants et petits-enfants, tout en restant calme. Pas d'agitation de village vacances, mais tout le confort.", items: [["La plage sans voiture", "Cinq minutes avec la poussette, sans chercher de parking."], ["Équipement bébé", "Lit, chaise haute et baignoire. Une valise en moins."], ["Jardin clos", "Jouer, manger et prendre un café en toute tranquillité."], ["Garage pour le matériel", "Vélos, poussettes, surf et matériel de plage à l'abri."], ["Forêt & dunes à proximité", "Promenades et pistes cyclables pour tous les âges."], ["Soirées au coin du feu", "Livres, jeux et un verre de vin quand il pleut dehors."]] },
    reviews: { title: "L'avis de ceux qui y ont séjourné.", lede: "Résumés d'avis contrôlés sur MediaVacances. Les points récurrents : situation, confort, accueil familial et communication rapide.", note: "Avis résumés à partir de MediaVacances.", source: "Voir l'annonce et les avis d'origine", platform: "MediaVacances", items: [["Deuxième séjour, toujours aussi satisfaits : maison pratique, excellent emplacement et enfants ravis.", "Août 2025"], ["Un séjour parfaitement organisé, sans point négatif signalé.", "Juin 2023"], ["Maison familiale agréable et confortable, très proche de la plage.", "Août 2020"], ["Maison de bon goût, bien équipée et idéale pour se détendre près de la plage.", "Nov. 2019"], ["Maison chaleureuse dans un quartier calme, tout près de la plage et du centre.", "Août 2019"], ["Maison joliment aménagée, proche de la mer et de la ville, avec de l'espace pour les familles.", "Mai 2018"]] },
    rates: { title: "Des tarifs clairs, sans surprise.", lede: "Le tarif hebdomadaire publié se situe entre 750 € et 1 150 €. Dany et Patricia confirment toujours le prix exact, la disponibilité et les frais pour vos dates.", from: "À partir de", max: "Tarif hebdomadaire publié maximum", week: "/semaine", adSource: "Selon l'annonce MediaVacances actuelle", exact: "Le prix exact dépend de la période et de la durée", low: ["Séjours possibles à partir de 2 nuits", "Week-end et milieu de semaine sur demande", "Aucun paiement lors de la première demande", "Confirmation personnelle par le propriétaire"], high: ["Demandez tôt pour les vacances scolaires", "Disponibilité vérifiée séparément", "Frais fixes indiqués dans l'offre", "Contrat de location avant paiement"], meta: [["Garantie", "500 €, remboursée après contrôle"], ["Acompte", "30 % à la réservation"], ["Ménage", "85 €, confirmé dans l'offre"], ["Taxe de séjour", "Confirmée dans l'offre"], ["Draps", "Option 12 € p.p."], ["Animal", "35 €/semaine, après accord"], ["Solde", "1 mois avant l'arrivée"]] },
    booking: { title: "Choisissez vos dates et obtenez une estimation.", body: "Le calcul donne une première indication selon la saison, le nombre de nuits, les voyageurs et les frais fixes. Dany et Patricia confirment ensuite personnellement la disponibilité, le prix total et les détails pratiques.", qualifiers: [["Aucun paiement immédiat.", "Vous préparez d'abord une demande sans engagement."], ["Une estimation, pas une promesse.", "Le prix final suit après vérification du calendrier et des frais."], ["Un contact personnel.", "Vous échangez avec le propriétaire, pas avec une agence."]], ownerNames: "Dany et Patricia", owners: "Propriétaires des Trois Loups", ownerNote: "Une maison familiale de caractère près de la mer, confortable pour plusieurs générations." },
    faq: { title: "Les réponses aux questions fréquentes.", lede: "Votre question n'est pas ici ? Envoyez un message via l'annonce MediaVacances vérifiée pour recevoir une réponse personnelle.", items: [["À quelle distance se trouve la plage ?", "Environ 100 mètres par une rue calme avec trottoir. Cinq minutes avec des enfants et le matériel de plage."], ["La maison convient-elle aux jeunes enfants ?", "Oui. Lit bébé, chaise haute et baignoire sont disponibles. Le jardin est entièrement clos."], ["Les animaux sont-ils admis ?", "En principe oui, uniquement après accord préalable. Mentionnez le type et le nombre d'animaux. Forfait de 35 €."], ["Y a-t-il un parking ?", "Une place privée et un garage intégré sont disponibles."], ["Y a-t-il le Wi-Fi ?", "Oui. Pour des besoins précis comme le télétravail vidéo, demandez la vitesse et la couverture."], ["Le linge de lit est-il compris ?", "Disponible en option (12 € p.p.) ou à apporter. Couettes et oreillers sont fournis."], ["Quelle est la durée minimale ?", "L'annonce indique des séjours à partir de 2 nuits. Le propriétaire confirme la durée minimale en période chargée."], ["Comment réserver ?", "Préparez votre demande ici, puis envoyez-la via MediaVacances. Le propriétaire confirme la disponibilité et l'offre finale."], ["Puis-je réserver un week-end ?", "Oui, hors haute saison, à partir de 2 nuits."], ["Les commerces et restaurants sont-ils proches ?", "Oui. Le centre d'Hardelot se trouve à environ 500 mètres."]] },
    contact: { title: "Une question, sans engagement ?", lede: "Choisissez d'abord vos dates. Pour la demande finale et les coordonnées vérifiées, nous vous renvoyons vers l'annonce MediaVacances existante.", ask: "Poser une question", check: "Vérifier la disponibilité", verified: "Contact vérifié", via: "Contacter via MediaVacances", note: "Contact direct avec le propriétaire · aucun paiement immédiat · conditions avant réservation.", listing: "Annonce MediaVacances" },
    footer: { region: "Côte d'Opale" },
    mobile: { from: "dès", week: "/sem.", check: "Voir le prix" }, lightbox: { close: "Fermer", previous: "Photo précédente", next: "Photo suivante" },
    form: { title: "Choisissez vos dates", from: "à partir de", week: "/ semaine", previousMonth: "Mois précédent", nextMonth: "Mois suivant", weekdays: ["Lu", "Ma", "Me", "Je", "Ve", "Sa", "Di"], selected: "Sélectionné", confirm: "Disponibilité confirmée personnellement", arrival: "Arrivée", departure: "Départ", adults: "Adultes", children: "Enfants", childrenSub: "jusqu'à 12 ans", decrease: "diminuer", increase: "augmenter", pet: "Animal", petSub: "Après accord, +35 €", petAria: "Ajouter un animal", name: "Nom", email: "E-mail", phone: "Téléphone", addMessage: "+ Ajouter un message", message: "Message (facultatif)", messagePlaceholder: "Heure d'arrivée, questions, détails…", cleaning: "Ménage", tax: "Taxe de séjour", toConfirm: "à confirmer", petFee: "Animal", total: "Estimation hors taxe", nights: "nuits", chooseDates: "Choisissez l'arrivée et le départ pour voir une estimation. Minimum 2 nuits.", submit: "Préparer ma demande", disclaimer: "Aucun paiement immédiat. Cette étape n'envoie encore rien ; vous vérifiez puis envoyez via MediaVacances.", ready: "Votre demande est prête.", readyBody: "Copiez le résumé, puis ouvrez l'annonce vérifiée pour l'envoyer au propriétaire.", copy: "Copier la demande", copied: "Demande copiée", open: "Ouvrir MediaVacances", priceTitle: "Estimation du prix", priceEmpty: "Sélectionnez d'abord l'arrivée et le départ. Le propriétaire confirme le prix final et la disponibilité.", attractive: "Période avantageuse", normal: "Estimation habituelle", busy: "Période chargée", attractiveText: "Cette période est avantageuse dans l'estimation. Le propriétaire vérifie ensuite le calendrier.", normalText: "Ce prix se situe dans la zone habituelle pour cette maison et cette période.", busyText: "Cette période est plus chère en raison de la saison, des vacances ou d'un court séjour.", period: "Période", guests: "Voyageurs", beach: "Plage", bedrooms: "Chambres", seasonHigh: "haute saison", seasonShoulder: "mi-saison", seasonChristmas: "vacances de Noël", seasonLow: "hors saison", yes: "oui", estimate: "Cette estimation n'est pas une garantie. Le prix final, la disponibilité et les conditions sont confirmés personnellement.", zone: "zone indicative", inquiryTitle: "Demande de réservation Les Trois Loups", preferredDates: "Dates souhaitées", party: "Groupe", adultsWord: "adulte(s)", childrenWord: "enfant(s)", petRequest: "animal sur demande", websitePrice: "Estimation du site (hors taxe de séjour à confirmer)", messageWord: "Message", requestConfirm: "Merci de confirmer la disponibilité, le prix total et les conditions.", toast: "Demande préparée pour le {from} → {to}. Copiez-la et envoyez-la via MediaVacances." }
  },

  en: {
    locale: "en-GB", htmlLang: "en", title: "Les Trois Loups · Holiday home in Hardelot", description: "Characterful family home 100 metres from Hardelot beach. Sleeps 6–8, with garden, wood burner and garage.",
    nav: { house: "The house", gallery: "Gallery", location: "Location", reviews: "Reviews", rates: "Rates", faq: "FAQ", cta: "Check dates", languages: "Choose language" },
    hero: { meta: "Les Trois Loups · Hardelot-Plage", title: "A proper family home, one hundred metres from the beach.", lede: "Space for six to eight guests, with four bedrooms, two bathrooms, a wood burner, garden and garage. The town centre is within walking distance.", cta: "Check price & preferred dates", photos: "See the real photos", features: "Key features", guests: "guests", bedrooms: "bedrooms", bathrooms: "bathrooms", sea: "to the sea" },
    trust: { label: "Booking reassurance", reviews: "Verified reviews", owners: "Direct with Dany and Patricia", payment: "No immediate payment" },
    about: { title: "A renovated character villa, not a holiday park.", lede: "Fully renovated while retaining its character. Ideal for families who want to stay near the sea without relying on a car — the beach, shops and restaurants are all within walking distance.", body: "Two floors, two bathrooms and an enclosed south-facing garden. The lounge with built-in wood burner is the heart of the house all year round. The garage has room for bikes, pushchairs, surfboards and beach equipment.", tags: ["Fully equipped kitchen", "Wood burner", "Enclosed garden", "South & west terraces", "Private parking", "Baby equipment"], imageSalon: "Lounge with wood burner", imageLiving: "Open-plan living and dining area", ground: "Ground floor", first: "First floor", groundRooms: ["Lounge with built-in wood burner", "Fully equipped open kitchen", "Bedroom with double bed", "Bathroom with bath/shower and double basin", "Separate WC · night hall"], firstRooms: ["Bedroom 2", "Bedroom 3", "Child/baby room with cot", "Shower room with basin and WC"], optional: "opt." },
    gallery: { title: "Through the house, then outside.", lede: "Current photos from the MediaHolidays listing, showing the real house and layout. Select any photo to enlarge it.", enlarge: "Enlarge", tabs: { buiten: "Outside & entrance", living: "Living & kitchen", slaap: "Bedrooms", bad: "Bathrooms" }, captions: { buiten: ["Les Trois Loups from the street", "Covered entrance", "Terrace with outdoor fireplace", "Private parking and integrated garage"], living: ["Living space and large dining table", "Lounge with wood burner", "Kitchen"], slaap: ["Bedroom with double bed", "Second double bedroom", "Room with two single beds", "Children's room", "High chair and baby equipment"], bad: ["Ground-floor bathroom", "Upstairs shower room"] } },
    amenities: { title: "Everything ready when you arrive.", lede: "Practically equipped for a family stay. Bed linen is optional; remaining details are confirmed with the final offer.", linen: "Bed linen and towels: optional (€12 p.p.) or bring your own.", items: [["Wi-Fi", "internet"], ["Television", "lounge"], ["Oven & microwave", ""], ["Washing machine", ""], ["Dishwasher", ""], ["Coffee maker & kettle", ""], ["Wood burner", ""], ["Barbecue & garden furniture", ""], ["Enclosed garden", "200 m²"], ["Private parking + garage", ""], ["Cot, high chair & baby bath", "ages 0–3"], ["Board games", ""], ["Library", "FR · NL · EN"], ["Bath & shower", ""], ["Pets", "on request"], ["Non-smoking home", "muted"]] },
    location: { title: "Close at hand, plenty to see.", lede: "From morning bread to a rainy-day outing: see at a glance what is walkable and what is worth a short drive.", introTitle: "Beach, town centre and daily essentials nearby.", intro: "Distances are indicative and based on the MediaHolidays listing. Always check current opening hours before an outing.", groups: [
      { label: "Close at hand", sub: "distances from the MediaHolidays listing", items: [["Beach access", "Sea and sand without the car", "± 100 m"], ["Hardelot centre", "Shops, bakery, restaurants and groceries", "± 500 m"], ["Dunes, forest and nature", "Walks, cycling and quiet routes nearby", "± 300 m"], ["Tennis club", "A nearby family sports option", "± 2.2 km"]] },
      { label: "Food & groceries", sub: "practical on arrival and every morning", items: [["Bakery & breakfast", "Bread, pastries and a beach picnic", "± 500 m"], ["Restaurants in Hardelot", "Lunch after the beach or dinner with children", "± 500 m"], ["Small grocery shop", "Handy when staying without a car", "± 500 m"], ["Larger supermarkets", "For the weekly shop", "short drive"]] },
      { label: "Things to do", sub: "rainy days, day trips and children", items: [["Château d'Hardelot", "Castle, gardens and cultural programme", "± 3 km"], ["Nausicaá Boulogne", "Large aquarium, ideal in poor weather", "10.4 km"], ["Maréis in Étaples", "Interactive discovery of fishing and marine life", "± 20 km"], ["Le Touquet", "Market, shops, golf and beach", "± 12 km"], ["Boulogne-sur-Mer", "Harbour, old town and restaurants", "± 14 km"], ["Bagatelle", "Family theme park for a full day out", "23.2 km"], ["Cap Blanc-Nez & Gris-Nez", "Cliffs, walking routes and views", "± 30 km"]] }
    ] },
    families: { title: "Why families come back.", lede: "The house works for holidays with children and grandchildren while still feeling calm. No holiday-park bustle, just the comforts you need.", items: [["Beach without the car", "Five minutes with the pushchair and no parking stress."], ["Baby equipment", "Cot, high chair and baby bath. One less suitcase."], ["Enclosed garden", "Space to play, eat and have coffee with peace of mind."], ["Garage for equipment", "Bikes, pushchairs, surfboards and beach gear all indoors."], ["Forest & dunes nearby", "Walking and cycling routes for all ages."], ["Evenings by the wood burner", "Books, games and a glass of wine when it rains outside."]] },
    reviews: { title: "What previous guests say.", lede: "Summaries of verified MediaHolidays reviews. The recurring themes are location, comfort, family friendliness and quick communication.", note: "Reviews are summarised from MediaHolidays.", source: "View the listing and source reviews", platform: "MediaHolidays", items: [["A second stay and just as pleased: a practical house, excellent location and happy children.", "Aug 2025"], ["A perfectly organised stay, with no drawbacks reported.", "Jun 2023"], ["A comfortable family home in a great location close to the beach.", "Aug 2020"], ["A tastefully equipped home, close to the beach and ideal for a relaxing stay.", "Nov 2019"], ["A cosy house in a quiet area, very close to the beach and centre, with responsive owners.", "Aug 2019"], ["A well-furnished home close to the sea and town, with quiet spaces for families.", "May 2018"]] },
    rates: { title: "Clear rates, no small print.", lede: "The published weekly rate ranges from €750 to €1,150. Dany and Patricia always confirm the exact price, availability and charges for your dates.", from: "From", max: "Maximum published weekly rate", week: "/week", adSource: "According to the current MediaHolidays listing", exact: "The exact rate depends on dates and length of stay", low: ["Stays from 2 nights possible", "Weekends and midweeks on request", "No payment with the first enquiry", "Personal confirmation from the owner"], high: ["Enquire early for school holidays", "Availability checked separately", "Fixed charges stated in the offer", "Rental agreement before payment"], meta: [["Deposit", "€500, returned after inspection"], ["Advance", "30% on booking"], ["Cleaning", "€85, confirmed in the offer"], ["Tourist tax", "Confirmed with the offer"], ["Bed linen", "Optional €12 p.p."], ["Pet", "€35/week, after approval"], ["Balance", "1 month before arrival"]] },
    booking: { title: "Choose your dates and get an instant estimate.", body: "The calculation gives a first indication based on season, nights, guests and fixed costs. Dany and Patricia then personally confirm availability, total price and practical arrangements.", qualifiers: [["No immediate payment.", "First prepare a no-obligation enquiry."], ["An estimate, not a promise.", "The final price follows after checking the calendar and costs."], ["Personal contact.", "You deal with the owner, not an agency."]], ownerNames: "Dany and Patricia", owners: "Owners of Les Trois Loups", ownerNote: "A characterful family home near the sea, with space for several generations." },
    faq: { title: "Answers to common questions.", lede: "Can't find your question? Send a message through the verified MediaHolidays listing for a personal reply.", items: [["How far away is the beach?", "About 100 metres along a quiet street with a pavement. Around five minutes with children and beach equipment."], ["Is the house suitable for young children?", "Yes. A cot, high chair and baby bath are available, and the garden is fully enclosed."], ["Are pets allowed?", "Usually, but only with prior approval. Include the type and number of pets in your enquiry. €35 fee."], ["Is parking available?", "There is private parking for one car and an integrated garage."], ["Is there Wi-Fi?", "Yes. Ask in advance about speed and coverage if you need reliable video calls."], ["Is bed linen included?", "Optional at €12 p.p., or bring your own. Duvets and pillows are provided."], ["What is the minimum stay?", "The listing states stays from 2 nights. The owner confirms minimum stays during busy periods."], ["How do I book?", "Prepare the enquiry here and send it through MediaHolidays. The owner confirms availability and sends a final offer."], ["Can I book a weekend or midweek?", "Yes, outside high season, from 2 nights."], ["Are shops and restaurants nearby?", "Yes. Hardelot centre is about 500 metres away."]] },
    contact: { title: "A question, with no obligation?", lede: "Choose your preferred dates first. For the final enquiry and verified contact details, we refer you to the existing MediaHolidays listing.", ask: "Ask a question", check: "Check availability", verified: "Verified contact", via: "Contact via MediaHolidays", note: "Direct contact with the private owner · no immediate payment · terms before booking.", listing: "MediaHolidays listing" },
    footer: { region: "Opal Coast" },
    mobile: { from: "from", week: "/week", check: "Check price" }, lightbox: { close: "Close", previous: "Previous photo", next: "Next photo" },
    form: { title: "Choose your preferred dates", from: "from", week: "/ week", previousMonth: "Previous month", nextMonth: "Next month", weekdays: ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"], selected: "Selected", confirm: "Availability confirmed personally", arrival: "Arrival", departure: "Departure", adults: "Adults", children: "Children", childrenSub: "up to age 12", decrease: "decrease", increase: "increase", pet: "Bringing a pet", petSub: "By agreement, +€35", petAria: "Bring a pet", name: "Name", email: "Email", phone: "Phone", addMessage: "+ Add a message", message: "Message (optional)", messagePlaceholder: "Arrival time, questions, details…", cleaning: "Cleaning", tax: "Tourist tax", toConfirm: "to confirm", petFee: "Pet", total: "Estimate excl. tax", nights: "nights", chooseDates: "Choose arrival and departure to see an estimate. Minimum 2 nights.", submit: "Prepare my enquiry", disclaimer: "No immediate payment. This step does not send anything yet; review it and then send it through MediaHolidays.", ready: "Your enquiry is ready.", readyBody: "Copy the summary, then open the verified listing to send it to the owner.", copy: "Copy enquiry", copied: "Enquiry copied", open: "Open MediaHolidays", priceTitle: "Price estimate", priceEmpty: "Select arrival and departure first. The owner confirms the final price and availability.", attractive: "Attractive period", normal: "Standard estimate", busy: "Busy period", attractiveText: "This period is favourable in the estimate. The owner checks the calendar afterwards.", normalText: "This price sits within the usual range for this house and period.", busyText: "This period costs more due to season, school holidays or a shorter stay.", period: "Period", guests: "Guests", beach: "Beach", bedrooms: "Bedrooms", seasonHigh: "high season", seasonShoulder: "shoulder season", seasonChristmas: "Christmas holiday", seasonLow: "low season", yes: "yes", estimate: "This estimate is indicative and not a price guarantee. Final price, availability and terms are confirmed personally.", zone: "guide range", inquiryTitle: "Les Trois Loups booking enquiry", preferredDates: "Preferred dates", party: "Party", adultsWord: "adult(s)", childrenWord: "child(ren)", petRequest: "pet on request", websitePrice: "Website estimate (excl. tourist tax to be confirmed)", messageWord: "Message", requestConfirm: "Please confirm availability, total price and terms.", toast: "Enquiry prepared for {from} → {to}. Copy it and send it through MediaHolidays." }
  }
};

const I18nContext = createContextI(null);
const SUPPORTED_LANGUAGES = ["nl", "fr", "en"];

function getInitialLanguage() {
  try {
    const queryLanguage = new URLSearchParams(window.location.search).get("lang");
    if (SUPPORTED_LANGUAGES.includes(queryLanguage)) return queryLanguage;
    const savedLanguage = window.localStorage.getItem("les-trois-loups-language");
    if (SUPPORTED_LANGUAGES.includes(savedLanguage)) return savedLanguage;
  } catch {}
  return "nl";
}

function I18nProvider({ children }) {
  const [lang, setLang] = useStateI(getInitialLanguage);
  const copy = SITE_COPY[lang];

  useEffectI(() => {
    document.documentElement.lang = copy.htmlLang;
    document.title = copy.title;
    const description = document.querySelector('meta[name="description"]');
    if (description) description.setAttribute("content", copy.description);
    try { window.localStorage.setItem("les-trois-loups-language", lang); } catch {}
  }, [lang, copy]);

  const value = useMemoI(() => ({ lang, setLang, copy, locale: copy.locale }), [lang, copy]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

function useI18n() {
  const value = useContextI(I18nContext);
  if (!value) throw new Error("useI18n must be used inside I18nProvider");
  return value;
}

Object.assign(window, { I18nProvider, useI18n, SITE_COPY, SUPPORTED_LANGUAGES });
